nelmio_api_doc:
    documentation:
        info:
            title: Kasta Test API
            description: This is a RESTful API for Kasta Test
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
