services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    networks:
      - app-kasta-network

  mysql_db:
    image: mysql:8.0
    env_file:
      - .env.local
    ports:
      - "3317:3306"
    volumes:
      - mysql_data_kasta:/var/lib/mysql
    networks:
      - app-kasta-network

volumes:
  mysql_data_kasta:

networks:
  app-kasta-network:
    driver: bridge